services:
  - type: web
    name: translatify-backend
    runtime: python
    rootDir: backend
    buildCommand: chmod +x build.sh && ./build.sh
    startCommand: gunicorn -w 1 -k eventlet --bind 0.0.0.0:$PORT app:app
    envVars:
      - key: WHISPER_MODEL
        value: base
      - key: HF_HOME
        value: /opt/render/project/src/.cache/huggingface
      - key: XDG_CACHE_HOME
        value: /opt/render/project/src/.cache
      - key: MONGO_URI
        sync: false
      - key: SECRET_KEY
        generateValue: true
